all:
	perl demo.pl
	perl button.pl
	perl shapes.pl
	perl piddle.pl
	perl tree.pl
	perl steganography.pl
	perl shadow_text.pl
	perl annotate.pl
	perl composite.pl
	perl pixel_fx.pl

clean:
	/bin/rm -f demo.jpg button.gif model.png shadow.gif tree.gif \
	  pixel_fx.gif
